disabled_rules: # rule identifiers to exclude from running
  - line_length
variable_name:
  min_length:
    warning: 2
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods